- name: Deploying frontend with Kubernetes
  hosts: localhost 
  gather_facts: false

  vars:
    namespace: "{{ namespace | default('frontendns') }}"
    image: "{{ image | default('cinesense-frontend:latest') }}"

      #roles:
      #- frontend
